collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.4953561
color:
  saturation: 0.5179211
  brandStrength: 0.4856631
  lightness: 0.5179211
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  rhythmicContrast: 0
layout_spectrum: 0.2759857
name: J. Travis Duncan
